"""Versioned, trusted project starters; no model calls and no product fabrication."""
from __future__ import annotations
import hashlib
import json
from pathlib import Path
import re
import shutil

TEMPLATE_ROOT = Path(__file__).parent / 'templates'
CACHE_ROOT = Path('/opt/atoms-template-cache/web-v1')
PYTHON_CACHE_ROOT = Path('/opt/atoms-template-cache/python-v1')
VERSION = '2026.10.07.1'
# A requested technology takes precedence, including versions and database choices.
STACK_WORDS = re.compile(r'(?<![a-z0-9])(?:react(?:\s*native)?|vue(?:js)?|nuxt|next(?:\.js|js)?|svelte(?:kit)?|angular|vite|preact|solid(?:js)?|astro|remix|fastapi|django|flask|express|nestjs|node(?:\.js|js)?|deno|bun|python|typescript|javascript|php|laravel|ruby|rails|golang|go|rust|java|spring(?:\s*boot)?|\.net|asp\.net|c#|postgres(?:ql)?|mysql|mongodb|sqlite|redis|mariadb|oracle|sqlserver|cockroachdb|mongodb|prisma|drizzle|html|css|js|sass|scss|jquery|webpack|supabase|firebase|cloudbase|electron|tauri|flutter|uni-app|tailwind|bootstrap)(?![a-z0-9])|微信(?:小程序|云开发)|小程序|鸿蒙', re.I)

def requested_stack(prompt, history=None):
    text = '\n'.join([str(item.get('content', '')) for item in (history or []) if item.get('role') == 'user'] + [prompt])
    return bool(STACK_WORDS.search(text))

def planner_contract(prompt, history=None):
    if requested_stack(prompt, history):
        return '用户提到了技术栈或数据库：优先准确遵循明确要求和版本，已有项目保持原栈；不要自动使用默认模板。其他未指定部分按需求决策。'
    return ('未指定技术栈的新 web 项目使用平台默认模板，不再执行 CLI 初始化：前端 Vite React TypeScript + shadcn/ui + Tailwind CSS，目录 frontend；'
            '默认采用轻量 demo-first 顺序：先确定最小 API/interface 契约（请求、响应、错误和模拟边界），再完成前端首屏与核心交互预览；后端持久化、外部服务接线和生产强化放在预览可用之后。'
            '只有共享数据、账号、跨设备同步、服务端计算、秘密凭据或用户明确要求真实后端时才启用 FastAPI + PostgreSQL 项目 Schema（平台数据库连接器），目录 backend；纯展示/本地工具使用 web-v1，确需服务端使用 fullstack-v1。'
            '执行器自动安装模板与锁定依赖，并交付实际源码及 docs/AGENT_GUIDE.md，无需规划创建脚手架、安装基线依赖或编写固定配置。'
            '现有项目保持架构；artifact/CLI/library/service 按真实需求处理，不能强加 web 模板。'
            '根 npm run build 输出 dist；系统检查真实代码、类型和接口，最后启动实际服务验收核心链路。可为当前改动编写和运行局部单元测试，但不将其作为最终验收标准。模板未含产品业务，必须实现完整需求。'
            '仅web默认模板要求commands.bootstrap=[]，build=["npm run build"]，test=[]，dev="npm run dev"。'
            '全栈不配置单元测试门槛；后端启动、路径代理、PostgreSQL Schema 持久化、一键Docker部署已配置。'
            'App.tsx 组合 pages/Index.tsx，领域模块放 lib，API客户端 lib/api.ts 的 api<T>(path, options)；后端 app/main.py 入口、routes.py 保持首个纵向切片简单路由，跨域/系统接口放 app/routers，Pydantic 合同放 app/schemas，业务规则放 app/services，db.py 保留 connection()/initialize()/database_schema()。保留基础函数名，在 initialize() 扩展真实业务表，不重写基线；按 schema -> service -> route -> UI 一次打通，不为每层单独规划任务。'
            '数据库连接器在创建项目时生成 project_<uuidhex> Schema 和独立应用角色，通过 APP_DATABASE_URL/APP_DATABASE_SCHEMA 注入后端；不得启动另一个 PostgreSQL Docker，不得读取平台管理员数据库凭据。psycopg 使用 %s 参数和 dict_row，PostgreSQL 用 ON CONFLICT、GENERATED BY DEFAULT AS IDENTITY；不要用 SQLite ?/PRAGMA/INSERT OR IGNORE。'
            '模板可能保留已有测试依赖；允许为当前改动生成和执行局部单元测试；最终不统一运行测试套件，验收使用系统代码检查与真实启动/HTTP/浏览器链路。'
            '简单完整应用优先用1–2个端到端业务任务，每个包含前端、必要API和验收；不要单列后端、前端、测试三个任务。需要后端的新项目最多安排三个阶段：T1 接口契约与模拟边界，T2 前端目标预览和交互，T3 后端真实接线/持久化/启动验收；T2 不得等待外部凭据。设计和接口描述保持精简，避免各字段重复同一需求。'
            'shadcn/ui 组件已预下载，@/ 别名指向 frontend/src；按照 frontend/README.md，先写根 DESIGN.md 的 Direction & Layout、Tokens、Shared Patterns & States、Media，已有文件沿用。将具体颜色、字体、排版、布局、响应式、状态、可访问性和媒体选择落实到实现，不添加独立设计审查循环。不创建浏览器favicon，除非用户明确要求。不要额外列初始化任务，直接以完整业务流程安排任务并验收。')

def select_template(plan, prompt, history=None):
    if requested_stack(prompt, history) or plan.get('application_type') != 'web':
        return None
    architecture = plan.get('architecture') or {}
    front = architecture.get('frontend') or {}
    back = architecture.get('backend') or {}
    stack = front.get('stack', '').lower()
    if front.get('directory') != 'frontend' or not all(word in stack for word in ('vite', 'react', 'typescript')):
        return None
    if back.get('required'):
        stack = back.get('stack', '').lower()
        if back.get('directory') != 'backend' or 'fastapi' not in stack or ('postgres' not in stack and 'postgres' not in str(architecture.get('persistence', '')).lower()):
            return None
        return 'fullstack-v1'
    return 'web-v1'

def template_files(name):
    if name not in {'web-v1', 'fullstack-v1'}:
        raise ValueError('Unknown platform template')
    result = {}
    for bundle in ['web-v1'] + (['api-v1'] if name == 'fullstack-v1' else []):
        for file in sorted((TEMPLATE_ROOT / bundle).rglob('*')):
            if file.is_file() and not file.is_symlink() and not set(file.parts).intersection({'node_modules','dist','__pycache__','.npm-cache'}):
                result[file.relative_to(TEMPLATE_ROOT / bundle).as_posix()] = file.read_text()
    return result

def install_template(root, name):
    """Preflight the entire installation. Existing application files are never overwritten."""
    files = template_files(name)
    digest = hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()
    manifest = {'name': name, 'version': VERSION, 'sha256': digest, 'files': sorted(files)}
    manifest_name = '.atoms/template.json'
    for relative in [*files, manifest_name]:
        target = root / relative
        if target.exists() or target.is_symlink() or not target.resolve().is_relative_to(root.resolve()):
            raise ValueError(f'模板安装拒绝覆盖已有文件或越界路径：{relative}')
    created = []
    try:
        for relative, content in {**files, manifest_name: json.dumps(manifest, ensure_ascii=False, indent=2)+'\n'}.items():
            target = root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            with target.open('x') as stream:
                created.append(target)
                stream.write(content)
    except BaseException:
        for target in reversed(created):
            target.unlink(missing_ok=True)
        raise
    return manifest

def dependency_fingerprint(root):
    return hashlib.sha256(b''.join((root/name).read_bytes() for name in ('package.json','package-lock.json','frontend/package.json'))).hexdigest()

def restore_dependency_cache(root, uid):
    """Copy, never share writable node_modules between tenants. Exact lock/manifests only."""
    import os
    if any((root/name).exists() for name in ('.npmrc','frontend/.npmrc')):
        return False
    dependency_dirs = [Path('node_modules'), Path('frontend/node_modules')]
    if any((root/path).exists() for path in dependency_dirs) or not (CACHE_ROOT/'fingerprint').is_file():
        return False
    try:
        if dependency_fingerprint(root) != (CACHE_ROOT/'fingerprint').read_text().strip():
            return False
    except OSError:
        return False
    # npm can hoist dependencies OR nest a version inside a workspace. Both
    # layouts are lockfile-resolved; copying only root modules silently loses packages.
    for relative in dependency_dirs:
        source = CACHE_ROOT/relative
        if not source.is_dir():
            continue
        destination = root/relative
        shutil.copytree(source, destination, symlinks=True)
        # npm workspaces link back to ../frontend; bin links stay within this copy.
        for directory, folders, files in os.walk(destination):
            for name in [directory, *(str(Path(directory)/n) for n in folders+files)]:
                if not Path(name).is_symlink():
                    os.chown(name, uid, uid)
    return True


def python_requirement_file(root):
    """Return the canonical project Python dependency manifest, if present."""
    for relative in ('backend/requirements.txt', 'requirements.txt'):
        if (root / relative).is_file():
            return root / relative
    return None


def python_dependency_fingerprint(root):
    requirement = python_requirement_file(root)
    if requirement is None:
        return None
    return hashlib.sha256(requirement.read_bytes()).hexdigest()


def restore_python_dependency_cache(root, uid, destination=None):
    """Copy the locked FastAPI/PostgreSQL environment into a tenant once.

    The image owns a read-only, lockfile-keyed wheel installation. Each project
    receives its own writable copy, so a new fullstack project does not perform
    another network pip install and tenants cannot mutate the shared cache.
    """
    fingerprint = python_dependency_fingerprint(root)
    if not fingerprint or not (PYTHON_CACHE_ROOT / 'fingerprint').is_file():
        return False
    try:
        if fingerprint != (PYTHON_CACHE_ROOT / 'fingerprint').read_text().strip():
            return False
    except OSError:
        return False
    destination = destination or root / '.python-packages'
    if destination.exists() and any(destination.iterdir()):
        return False
    source = PYTHON_CACHE_ROOT / '.python-packages'
    if not source.is_dir():
        return False
    shutil.copytree(source, destination, symlinks=True, dirs_exist_ok=True)
    import os
    for directory, folders, files in os.walk(destination):
        for name in [directory, *(str(Path(directory) / n) for n in folders + files)]:
            if not Path(name).is_symlink():
                os.chown(name, uid, uid)
    return True
