"""Disposable real PostgreSQL/MinIO/coordinator integration, opt-in in live stack."""
import os
import uuid
import unittest
import threading
from fastapi.testclient import TestClient
from psycopg import sql
from psycopg.types.json import Jsonb
from main import app,connection,current_user,grant_project_role
from agent import ensure_workspace,project_root,project_uid
from project_database import names
from account import ensure_profile
from referrals import attribute,message_reward,publish_reward

@unittest.skipUnless(os.getenv('RUN_MENU_DATABASE_TESTS')=='1','requires running PostgreSQL, MinIO and coordinator')
class ProjectMenuApiTests(unittest.TestCase):
    def setUp(self):
        self.user={'id':uuid.uuid4(),'email':'menu-'+uuid.uuid4().hex+'@example.test'}
        self.project=uuid.uuid4();self.projects=[self.project];self.extra_users=[]
        with connection() as c:
            c.execute("INSERT INTO users(id,email,password_hash) VALUES(%s,%s,'test-only')",(self.user['id'],self.user['email']))
            ensure_profile(c,self.user)
            c.execute("INSERT INTO projects(id,owner_id,title,prompt,workspace_path,status,preview_html) VALUES(%s,%s,'menu fixture','fixture',%s,'ready','<h1>fixture</h1>')",(self.project,self.user['id'],f'projects/{self.project.hex}'))
            grant_project_role(c,self.project)
            schema,_=names(self.project)
            c.execute(sql.SQL('SET LOCAL ROLE {}').format(sql.Identifier(names(self.project)[1])))
            c.execute(sql.SQL('CREATE TABLE {}.items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT)').format(sql.Identifier(schema)))
            c.execute(sql.SQL('INSERT INTO {}.items(name) VALUES(%s)').format(sql.Identifier(schema)),('original',))
        self.root=ensure_workspace(self.project,self.user['id']);(self.root/'index.html').write_text('<html><head></head><body><h1>fixture</h1></body></html>');(self.root/'dist').mkdir();(self.root/'dist'/'index.html').write_text((self.root/'index.html').read_text());(self.root/'.env').write_text('do not copy')
        self.client=TestClient(app);app.dependency_overrides[current_user]=lambda:self.user
        self.url='/api/projects/'+str(self.project)
    def tearDown(self):
        app.dependency_overrides[current_user]=lambda:self.user
        for project in reversed(self.projects):self.assertIn(self.client.delete('/api/projects/'+str(project)).status_code,(204,404))
        app.dependency_overrides.clear();self.client.close()
        with connection() as c:
            for user in self.extra_users:c.execute('DELETE FROM users WHERE id=%s',(user,))
            c.execute('DELETE FROM users WHERE id=%s',(self.user['id'],))
    def test_database_browser_real_rows_pagination_and_owner_isolation(self):
        listed=self.client.get(self.url+'/database/tables')
        self.assertEqual(listed.status_code,200,listed.text)
        self.assertEqual(listed.json()['tables'],[{'name':'items'}])
        with connection() as c:
            c.execute(sql.SQL('INSERT INTO {}.items(name) VALUES(%s)').format(sql.Identifier(names(self.project)[0])),('second',))
        first=self.client.get(self.url+'/database/tables',params={'table':'items','limit':1}).json()
        self.assertEqual(first['rows'][0]['name'],'original')
        self.assertTrue(first['has_more'])
        second=self.client.get(self.url+'/database/tables',params={'table':'items','limit':1,'offset':1}).json()
        self.assertEqual(second['rows'][0]['name'],'second')
        self.assertFalse(second['has_more'])
        self.assertEqual(self.client.get(self.url+'/database/tables',params={'table':'public.users'}).status_code,404)
        self.assertEqual(self.client.get(self.url+'/database/tables',params={'table':'items; DROP SCHEMA public'}).status_code,404)
        self.assertEqual(self.client.get(self.url+'/database/tables',params={'limit':101}).status_code,422)
        app.dependency_overrides[current_user]=lambda:{'id':uuid.uuid4(),'email':'foreign@example.test'}
        self.assertEqual(self.client.get(self.url+'/database/tables').status_code,404)

    def test_clone_independent_schema_current_files_and_preview(self):
        for data,expected in [(False,0),(True,1)]:
            response=self.client.post(self.url+'/clone',json={'title':'clone','copy_database':data});self.assertEqual(response.status_code,201,response.text)
            clone=uuid.UUID(response.json()['id']);self.projects.append(clone)
            root=project_root(clone);self.assertTrue((root/'index.html').exists());self.assertTrue((root/'dist'/'index.html').exists());self.assertFalse((root/'.env').exists());self.assertEqual((root/'dist').stat().st_uid,project_uid(clone));self.assertEqual((root/'dist'/'index.html').stat().st_uid,project_uid(clone))
            self.assertTrue(response.json()['preview_html']);self.assertFalse(response.json()['published'])
            schema,role=names(clone)
            with connection() as c:
                self.assertEqual(c.execute(sql.SQL('SELECT COUNT(*) AS count FROM {}.items').format(sql.Identifier(schema))).fetchone()['count'],expected)
                self.assertEqual(c.execute('SELECT r.rolname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_roles r ON r.oid=c.relowner WHERE n.nspname=%s AND c.relname=%s',(schema,'items')).fetchone()['rolname'],role)
                c.execute(sql.SQL('SET LOCAL ROLE {}').format(sql.Identifier(role)))
                self.assertEqual(c.execute(sql.SQL('INSERT INTO {}.items(name) VALUES(%s) RETURNING id').format(sql.Identifier(schema)),('new',)).fetchone()['id'],expected+1)
    def test_publish_badge_privacy_and_unpublish(self):
        self.client.patch(self.url,json={'visibility':'private'})
        self.assertEqual(self.client.patch(self.url,json={'published':True}).status_code,409)
        self.client.patch(self.url,json={'visibility':'public'})
        response=self.client.patch(self.url,json={'published':True});self.assertEqual(response.status_code,200,response.text)
        slug='menu-'+self.project.hex[:12]
        self.assertEqual(self.client.patch(self.url,json={'publish_slug':slug}).status_code,200)
        self.assertEqual(self.client.get('/api/sites/'+slug).status_code,200)
        public='/api/public/'+str(self.project);self.assertIn('data-atoms-badge',self.client.get(public+'?__atoms_frame=1').text)
        self.assertEqual(self.client.patch(self.url,json={'remove_badge':True,'favorite':True,'title':'new title'}).status_code,200)
        self.assertNotIn('data-atoms-badge',self.client.get(public+'?__atoms_frame=1').text)
        row=self.client.get(self.url).json();self.assertTrue(row['favorite']);self.assertEqual(row['title'],'new title')
        self.client.patch(self.url,json={'visibility':'private'});self.assertEqual(self.client.get(public).status_code,404);self.assertEqual(self.client.get('/api/sites/'+slug).status_code,404)
        self.client.patch(self.url,json={'visibility':'public'});self.assertEqual(self.client.get(public).status_code,200)
        self.client.patch(self.url,json={'published':False});self.assertEqual(self.client.get(public).status_code,404)
    def test_domain_pending_and_ownership_scope(self):
        endpoint=self.url+'/domains';self.assertEqual(self.client.post(endpoint,json={'domain':'https://invalid.test'}).status_code,422)
        name='menu-'+uuid.uuid4().hex+'.example.com'
        response=self.client.post(endpoint,json={'domain':name});self.assertEqual(response.status_code,201,response.text);self.assertEqual(response.json()['status'],'pending')
        self.assertEqual(len(self.client.get(endpoint).json()['domains']),1)
        app.dependency_overrides[current_user]=lambda:{'id':uuid.uuid4()}
        self.assertEqual(self.client.get(endpoint).status_code,404)
        app.dependency_overrides[current_user]=lambda:self.user
        self.assertEqual(self.client.delete(endpoint+'/'+name).status_code,204)
    def test_busy_clone_and_cross_owner_rejected(self):
        with connection() as c:c.execute("UPDATE projects SET status='running' WHERE id=%s",(self.project,))
        self.assertEqual(self.client.post(self.url+'/clone',json={'title':'busy'}).status_code,409)
        app.dependency_overrides[current_user]=lambda:{'id':uuid.uuid4()}
        self.assertEqual(self.client.post(self.url+'/clone',json={'title':'foreign'}).status_code,404)
    def test_clone_waits_for_brief_preview_mutation(self):
        with connection() as lock:
            lock.execute('SELECT pg_advisory_lock_shared(hashtextextended(%s,17))',(str(self.project),))
            timer=threading.Timer(0.3,lambda:lock.execute('SELECT pg_advisory_unlock_shared(hashtextextended(%s,17))',(str(self.project),)))
            timer.start()
            response=self.client.post(self.url+'/clone',json={'title':'after preview'})
            timer.join()
            self.assertEqual(response.status_code,201,response.text)
            self.projects.append(uuid.UUID(response.json()['id']))
    def test_referral_rewards_are_real_and_idempotent(self):
        invitee={'id':uuid.uuid4(),'email':'referral-'+uuid.uuid4().hex+'@example.test'};self.extra_users.append(invitee['id'])
        code=self.client.get('/api/account/referrals').json()['code']
        with connection() as c:
            c.execute("INSERT INTO users(id,email,password_hash) VALUES(%s,%s,'test-only')",(invitee['id'],invitee['email']));ensure_profile(c,invitee);attribute(c,invitee['id'],code)
            before=c.execute('SELECT credits FROM account_profiles WHERE user_id=%s',(self.user['id'],)).fetchone()['credits']
            message_reward(c,invitee);message_reward(c,invitee);publish_reward(c,invitee);publish_reward(c,invitee)
            self.assertEqual(c.execute('SELECT credits FROM account_profiles WHERE user_id=%s',(invitee['id'],)).fetchone()['credits'],25)
            self.assertEqual(c.execute('SELECT credits FROM account_profiles WHERE user_id=%s',(self.user['id'],)).fetchone()['credits'],before+10)
            self.assertEqual(c.execute("SELECT COUNT(*) AS count FROM account_transactions WHERE user_id=%s AND kind='referral_publish'",(self.user['id'],)).fetchone()['count'],1)
