"""Real connector integration against the existing platform PostgreSQL instance.

Opt in with ATOMS_TEST_DATABASE_URL. Only randomly named test projects are
created/deleted; never recreate the platform database or customer schemas.
"""
import os
import subprocess
import sys
import tempfile
import unittest
import uuid
from pathlib import Path
from unittest.mock import patch
import psycopg
from psycopg import sql
from psycopg.rows import dict_row
import project_database as connector
import project_templates


class ConnectorIdentityTests(unittest.TestCase):
    def test_downloaded_credentials_are_excluded_from_agent_context(self):
        import agent
        with tempfile.TemporaryDirectory() as folder:
            root=Path(folder)
            (root/'env.connector').write_text('APP_DATABASE_URL=private')
            (root/'README.md').write_text('public')
            self.assertEqual(agent.list_files(root),['README.md'])
            for name in ['env.connector','nested/env.connector','nested/.env.connector']:
                with self.assertRaises(ValueError):
                    agent.safe_file(root,name)

    def test_identifiers_and_worker_binding(self):
        project = uuid.uuid4()
        self.assertEqual(connector.names(project), ('project_'+project.hex, 'atoms_app_'+project.hex))
        with self.assertRaises(ValueError):
            connector.names('p001; DROP SCHEMA public')
        with patch.dict(os.environ, {'PROJECT_ID':str(project)}):
            with self.assertRaisesRegex(ValueError, '跨项目'):
                connector.environment(uuid.uuid4())
        with patch.dict(os.environ, {'PROJECT_ID':str(project), 'APP_DATABASE_URL':'postgresql://example', 'APP_DATABASE_SCHEMA':'public'}):
            with self.assertRaisesRegex(ValueError, '不匹配'):
                connector.environment(project)


@unittest.skipUnless(os.getenv('ATOMS_TEST_DATABASE_URL'), 'requires explicit real PostgreSQL integration opt-in')
class ManagedDatabaseTests(unittest.TestCase):
    def setUp(self):
        self.url = os.environ['ATOMS_TEST_DATABASE_URL']
        self.projects = [uuid.uuid4(), uuid.uuid4()]
        with self.admin() as db:
            connector.init_connector(db)
            for project in self.projects:
                db.execute('INSERT INTO public.projects(id,title,prompt) VALUES(%s,%s,%s)', (project,'Connector integration test','isolated fixture'))
                connector.provision(db,project,self.url)

    def admin(self):
        return psycopg.connect(self.url,row_factory=dict_row)

    def app(self, index=0):
        return psycopg.connect(connector.credentials(self.projects[index],self.url)[3],row_factory=dict_row)

    def tearDown(self):
        with self.admin() as db:
            for project in self.projects:
                connector.remove(db,project)
                db.execute('DELETE FROM public.projects WHERE id=%s',(project,))

    def test_isolation_persistence_idempotence_and_delete(self):
        for index in range(2):
            with self.app(index) as db:
                state=db.execute('SELECT current_schema() AS schema,current_user AS role').fetchone()
                self.assertEqual((state['schema'],state['role']),connector.names(self.projects[index]))
                db.execute('CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL)')
                db.execute('INSERT INTO orders(name) VALUES(%s)',('project-'+str(index),))
        for query in [sql.SQL('SELECT * FROM {}.orders').format(sql.Identifier(connector.names(self.projects[1])[0])),sql.SQL('SELECT * FROM public.projects'),sql.SQL('CREATE TABLE public.intrusion(id int)'),sql.SQL('CREATE SCHEMA intrusion')]:
            with self.assertRaises(psycopg.errors.InsufficientPrivilege):
                with self.app() as db:
                    db.execute(query)
        with self.admin() as db:
            connector.provision(db,self.projects[0],self.url)
            metadata=connector.metadata(db,self.projects[0])
            self.assertEqual(metadata['schema'],connector.names(self.projects[0])[0])
            self.assertNotIn('password',metadata)
        with self.app() as db:
            self.assertEqual(db.execute('SELECT name FROM orders').fetchone()['name'],'project-0')
        with self.assertRaises(ValueError):
            with self.app() as db:
                db.execute('INSERT INTO orders(name) VALUES(%s)',('rollback',))
                raise ValueError('abort')
        with self.app() as db:
            self.assertEqual(db.execute('SELECT COUNT(*) AS count FROM orders').fetchone()['count'],1)
        with self.admin() as db:
            connector.remove(db,self.projects[0])
        with self.admin() as db:
            schema,role=connector.names(self.projects[0])
            self.assertIsNone(db.execute('SELECT 1 FROM pg_namespace WHERE nspname=%s',(schema,)).fetchone())
            self.assertIsNone(db.execute('SELECT 1 FROM pg_roles WHERE rolname=%s',(role,)).fetchone())
        with self.app(1) as db:
            self.assertEqual(db.execute('SELECT name FROM orders').fetchone()['name'],'project-1')

    def test_actual_template_health_transaction_and_restart(self):
        with tempfile.TemporaryDirectory() as folder:
            root=Path(folder)
            project_templates.install_template(root,'fullstack-v1')
            schema,_,_,url=connector.credentials(self.projects[0],self.url)
            env={**os.environ,'APP_DATABASE_URL':url,'APP_DATABASE_SCHEMA':schema,'PYTHONPATH':folder}
            result=subprocess.run([sys.executable,'-m','unittest','discover','-s','backend/tests','-v'],cwd=root,env=env,text=True,capture_output=True,timeout=45)
            self.assertEqual(result.returncode,0,result.stdout+result.stderr)
            self.assertIn('Ran 1 test',result.stderr)
            self.assertNotIn('skipped',result.stderr)
